vim.g.mapleader = " "
vim.keymap.set("n", "<leader>E", vim.cmd.Ex, { remap = false, desc = "Open Tree" })
vim.keymap.set("n", "<leader>f", function() vim.lsp.buf.format() end, { remap = false, desc = "Format" })
vim.keymap.set("n", "<leader>bn", vim.cmd.bnext, { remap = false, desc = "Next buffer" })
vim.keymap.set("n", "<leader>bb", vim.cmd.bprev, { remap = false, desc = "Previous buffer" })
vim.keymap.set("n", "<leader>bd", vim.cmd.bd, { remap = false, desc = "Delete buffer" })
vim.keymap.set("n", "<leader>h", vim.cmd.nohlsearch, { remap = false, desc = "Clear Highlights" })
vim.keymap.set({ "n" }, "<leader>Fl", ":vnew | buffer __FLUTTER_DEV_LOG__<CR>", { remap = false, desc = "Open flutter dev log in vertical split" })
vim.keymap.set("n", "<leader>Fr", vim.cmd.FlutterRun, { remap = false, desc = "FlutterRun" })
vim.keymap.set("n", "<leader>Fq", vim.cmd.FlutterQuit, { remap = false, desc = "FlutterQuit" })
