-- document existing key chains
require('which-key').add(
--[[  ['<leader>c'] = { name = '[C]ode', _ = 'which_key_ignore' },
  ['<leader>d'] = { name = '[D]ocument', _ = 'which_key_ignore' },
  ['<leader>g'] = { name = '[G]it', _ = 'which_key_ignore' },
  ['<leader>h'] = { name = 'More git', _ = 'which_key_ignore' },
  ['<leader>r'] = { name = '[R]ename', _ = 'which_key_ignore' },
  ['<leader>s'] = { name = '[S]earch', _ = 'which_key_ignore' },
  ['<leader>w'] = { name = '[W]orkspace', _ = 'which_key_ignore' },
  ['<leader>b'] = { name = '[B]uffers', _ = 'which_key_ignore' },
  ['<leader>t'] = { name = '[T]elescope', _ = 'which_key_ignore' },
  ['g'] = { name = '[G]O!!!', _ = 'which_key_ignore' }, ]]
  {
    { "<leader>b",  group = "[B]uffers" },
    { "<leader>b_", hidden = true },
    { "<leader>c",  group = "[C]ode" },
    { "<leader>c_", hidden = true },
    { "<leader>d",  group = "[D]ocument" },
    { "<leader>d_", hidden = true },
    { "<leader>g",  group = "[G]it" },
    { "<leader>g_", hidden = true },
    { "<leader>h",  group = "More git" },
    { "<leader>h_", hidden = true },
    { "<leader>r",  group = "[R]ename" },
    { "<leader>r_", hidden = true },
    { "<leader>s",  group = "[S]earch" },
    { "<leader>s_", hidden = true },
    { "<leader>t",  group = "[T]elescope" },
    { "<leader>t_", hidden = true },
    { "<leader>w",  group = "[W]orkspace" },
    { "<leader>w_", hidden = true },
    { "g",          group = "[G]O!!!" },
    { "g_",         hidden = true },
  }
)
